name: your_app_name
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6  # Check for the latest version on pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Check for the latest version on pub.dev

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application so that you can use the icons in
  # the Material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_telikoCOLOURED-02.svg
    - assets/images/logo_telikoCOLOURED-02ORANGE-01.svg
    - assets/images/backmodel.png
    - assets/images/gButton.png
    - assets/images/key.png
    - assets/images/key2.png
    - assets/images/tButton.png
    - assets/images/bulbEUR.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
