name: s
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  http: ^1.2.1
  image_picker: ^0.8.4+8
  charts_flutter: ^0.12.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.1.59
  image_gallery_saver: ^1.7.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_telikoCOLOURED-02.svg
    - assets/images/logo_telikoCOLOURED-02ORANGE-01.svg
    - assets/images/lamp_selected.svg
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/user3.png
    - assets/images/user4.png
    - assets/images/user5.png
    - assets/images/iconM1.png
    - assets/images/iconM2.png
    - assets/images/iconM3.png
    - assets/images/iconM4.png
    - assets/images/iconM5.png
